services:
  app:
    build:
      context: .
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./history:/app/history
      - ./config.json:/app/config.json
    restart: unless-stopped
